
package br.gov.esocial.servicos.empregador.envio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicoEnviarLoteEventos", targetNamespace = "http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0", wsdlLocation = "file:/C:/Users/Leandro%20Albanez/OneDrive%20-%20Atlantic%20Solutions/Documenta\u00e7\u00e3o%20Esocial/Pacote%20de%20Comunica\u00e7\u00e3o%20eSocial%20v1.4.1/WSDL/WsEnviarLoteEventos-v1_1_0.wsdl")
public class ServicoEnviarLoteEventos_Service
    extends Service
{

    private final static URL SERVICOENVIARLOTEEVENTOS_WSDL_LOCATION;
    private final static WebServiceException SERVICOENVIARLOTEEVENTOS_EXCEPTION;
    private final static QName SERVICOENVIARLOTEEVENTOS_QNAME = new QName("http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0", "ServicoEnviarLoteEventos");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://webservices.producaorestrita.esocial.gov.br/servicos/empregador/enviarloteeventos/WsEnviarLoteEventos.svc?singleWsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICOENVIARLOTEEVENTOS_WSDL_LOCATION = url;
        SERVICOENVIARLOTEEVENTOS_EXCEPTION = e;
    }

    public ServicoEnviarLoteEventos_Service() {
        super(__getWsdlLocation(), SERVICOENVIARLOTEEVENTOS_QNAME);
    }

    public ServicoEnviarLoteEventos_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICOENVIARLOTEEVENTOS_QNAME, features);
    }

    public ServicoEnviarLoteEventos_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICOENVIARLOTEEVENTOS_QNAME);
    }

    public ServicoEnviarLoteEventos_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICOENVIARLOTEEVENTOS_QNAME, features);
    }

    public ServicoEnviarLoteEventos_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicoEnviarLoteEventos_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicoEnviarLoteEventos
     */
    @WebEndpoint(name = "WsEnviarLoteEventos")
    public ServicoEnviarLoteEventos getWsEnviarLoteEventos() {
        return super.getPort(new QName("http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0", "WsEnviarLoteEventos"), ServicoEnviarLoteEventos.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicoEnviarLoteEventos
     */
    @WebEndpoint(name = "WsEnviarLoteEventos")
    public ServicoEnviarLoteEventos getWsEnviarLoteEventos(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0", "WsEnviarLoteEventos"), ServicoEnviarLoteEventos.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICOENVIARLOTEEVENTOS_EXCEPTION!= null) {
            throw SERVICOENVIARLOTEEVENTOS_EXCEPTION;
        }
        return SERVICOENVIARLOTEEVENTOS_WSDL_LOCATION;
    }

}
